services:
  - type: web
    name: seekai
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn ai_learning_hub.wsgi:application"
    healthCheckPath: /health/
    autoDeploy: true
    disk:
      name: static
      mountPath: /opt/render/project/src/staticfiles
      sizeGB: 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        fromDatabase:
          name: seekai_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: 4
      - key: OPENAI_API_KEY
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DJANGO_SETTINGS_MODULE
        value: "ai_learning_hub.settings"

  - type: redis
    name: seekai-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction

databases:
  - name: seekai_db
    databaseName: seekai
    plan: free
    ipAllowList: [] 